language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

script:
  - >
    echo;
    echo "Running unit tests";
    mkdir -p build/logs;
    php vendor/bin/phpunit --colors -c tests/phpunit.xml --coverage-clover build/logs/clover.xml;

after_script:
  - php vendor/bin/coveralls -v;
