language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true

script:
  - >
    echo;
    echo "Running unit tests";
    mkdir -p build/logs;
    if [[ $(phpenv version-name) == '5.6' ]]; then php vendor/bin/phpunit --colors \
     -c tests/phpunit.xml \--coverage-clover build/logs/clover.xml ; fi ;
    if [[ $(phpenv version-name) != '5.6' ]]; then php vendor/bin/phpunit --colors -c tests/phpunit.xml ; fi ;

after_script:
  - >
    if [[ $(phpenv version-name) == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar \
    code-coverage:upload --format=php-clover build/logs/clover.xml ; fi;
